[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node scripts/migrate.mjs && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
